Add ability to download cover art to mpplus command, add option to download_cover_art to specify alternate music directory

diff --git a/bin/download_cover_art b/bin/download_cover_art
--- a/bin/download_cover_art
+++ b/bin/download_cover_art
@@ -2,21 +2,57 @@
 #
 # Uses sacad from https://github.com/desbma/sacad
 
-mpd_music=`grep ^music_directory /etc/mpd.conf`
-[ "${mpd_music}" ] || mpd_music=`grep \#music_directory /etc/mpd.conf`
-mpd_music=`echo ${mpd_music} | awk ' { print $2 } ' | sed -e "s/\"//g"`
-[ "${mpd_music}" ] || {
-  echo "Could not detect any music_directory setting in /etc/mpd.conf."
-  echo "Set the music_directory setting in /etc/mpd.conf and rerun this command."
-  echo "Exiting."
+usage() {
+  printf "\nUsage: download_cover_art [-d music_directory] [-u]"
+  printf "\n\nWithout the '-d music_directory' option, the 'music_directory'"
+  printf "\nsetting in '/etc/mpd.conf' will be used\n\n"
   exit 1
 }
+
+mpd_music=
+custom_dir=
+while getopts "d:u" flag; do
+    case $flag in
+        d)
+            mpd_music="$OPTARG"
+            custom_dir=1
+            ;;
+        u)
+            usage
+            ;;
+    esac
+done
+
+[ "${mpd_music}" ] || {
+  mpd_music=`grep ^music_directory /etc/mpd.conf`
+  [ "${mpd_music}" ] || mpd_music=`grep \#music_directory /etc/mpd.conf`
+  mpd_music=`echo ${mpd_music} | awk ' { print $2 } ' | sed -e "s/\"//g"`
+  [ "${mpd_music}" ] || {
+    echo "Could not detect any music_directory setting in /etc/mpd.conf."
+    echo "Set the music_directory setting in /etc/mpd.conf and rerun this command."
+    echo "Exiting."
+    exit 1
+  }
+}
+
 [ -d "${mpd_music}" ] || {
-  echo "music_directory setting in /etc/mpd.conf:
+  if [ "${custom_dir}" ]
+  then
+    echo "Specified music directory:"
+  else
+    echo "music_directory setting in /etc/mpd.conf:"
+  fi
   echo "    ${mpd_music}"
   echo "Does not exist or is not a directory."
   echo ""
-  echo "Set the music_directory setting in /etc/mpd.conf and rerun this command."
+  if [ "${custom_dir}" ]
+  then
+    echo "Rerun this command with the '-d music_directory' option providing"
+    echo "a valid path to a music directory or without the -d option"
+    echo "to use the music_directory setting in '/etc/mpd.conf'"
+  else
+    echo "Set the music_directory setting in /etc/mpd.conf and rerun this command."
+  fi
   echo "Exiting."
   exit 1
 }
