Use ~/.config/mpd/mdp.conf for music_directory, move mpcplus-tmux to config/mpcplus-art.sh

diff --git a/bin/download_cover_art b/bin/download_cover_art
--- a/bin/download_cover_art
+++ b/bin/download_cover_art
@@ -2,10 +2,12 @@
 #
 # Uses sacad from https://github.com/desbma/sacad
 
+MPD_CONF=~/.config/mpd/mpd.conf
+
 usage() {
   printf "\nUsage: download_cover_art [-d music_directory] [-u]"
   printf "\n\nWithout the '-d music_directory' option, the 'music_directory'"
-  printf "\nsetting in '/etc/mpd.conf' will be used\n\n"
+  printf "\nsetting in ${MPD_CONF} will be used\n\n"
   exit 1
 }
 
@@ -23,13 +25,29 @@ while getopts "d:u" flag; do
     esac
 done
 
+[ "${custom_dir}" ] || {
+  [ -f ${MPD_CONF} ] || {
+    if [ -f /etc/mpd.conf ]
+    then
+      MPD_CONF=/etc/mpd.conf
+    else
+      echo "Could not locate ${MPD_CONF}"
+      echo "Music directory can be specified using the '-d directory' option"
+      echo "Exiting"
+      usage
+    fi
+  }
+}
+
 [ "${mpd_music}" ] || {
-  mpd_music=`grep ^music_directory /etc/mpd.conf`
-  [ "${mpd_music}" ] || mpd_music=`grep \#music_directory /etc/mpd.conf`
+  mpd_music=`grep ^music_directory ${MPD_CONF}`
+  [ "${mpd_music}" ] || mpd_music=`grep \#music_directory ${MPD_CONF}`
   mpd_music=`echo ${mpd_music} | awk ' { print $2 } ' | sed -e "s/\"//g"`
+  # Need to expand the tilda to $HOME
+  mpd_music="${mpd_music/#\~/$HOME}"
   [ "${mpd_music}" ] || {
-    echo "Could not detect any music_directory setting in /etc/mpd.conf."
-    echo "Set the music_directory setting in /etc/mpd.conf and rerun this command."
+    echo "Could not detect any music_directory setting in ${MPD_CONF}."
+    echo "Set the music_directory setting in ${MPD_CONF} and rerun this command."
     echo "Exiting."
     exit 1
   }
@@ -40,7 +58,7 @@ done
   then
     echo "Specified music directory:"
   else
-    echo "music_directory setting in /etc/mpd.conf:"
+    echo "music_directory setting in ${MPD_CONF}:"
   fi
   echo "    ${mpd_music}"
   echo "Does not exist or is not a directory."
@@ -49,15 +67,23 @@ done
   then
     echo "Rerun this command with the '-d music_directory' option providing"
     echo "a valid path to a music directory or without the -d option"
-    echo "to use the music_directory setting in '/etc/mpd.conf'"
+    echo "to use the music_directory setting in ${MPD_CONF}"
   else
-    echo "Set the music_directory setting in /etc/mpd.conf and rerun this command."
+    echo "Set the music_directory setting in ${MPD_CONF} and rerun this command."
   fi
   echo "Exiting."
   exit 1
 }
 
-pip list | grep sacad > /dev/null || python -m pip install sacad
+have_sacad=`type -p sacad_r`
+[ "${have_sacad}" ] || {
+  if pip list | grep sacad > /dev/null
+  then
+    python -m pip install --upgrade sacad
+  else
+    python -m pip install sacad
+  fi
+}
 
 cd ${mpd_music}
 for artist in *
