Add beets, tmux plugin manager, use HOME/Music for MPD by default

diff --git a/bin/mpcinit b/bin/mpcinit
--- a/bin/mpcinit
+++ b/bin/mpcinit
@@ -9,79 +9,12 @@
 MPPCDIR=/usr/share/musicplayerplus
 CONFDIR=${MPPCDIR}/mpcplus
 SCPTDIR=${MPPCDIR}/scripts
+MPDCONFDIR="${HOME}/.config/mpd"
+MPDCONF="${MPDCONFDIR}/mpd.conf"
+BEETSCONFDIR="${HOME}/.config/beets"
+BEETSCONF="${BEETSCONFDIR}/config.yaml"
 CFGS="config-art.conf default_cover.png fzmp.conf"
 SCPS="album_cover.sh cover_obs.sh mpcplus-art.sh mppsplash-dual.sh"
-
-[ -f ${CONFDIR}/config ] || {
-    echo "${CONFDIR}/config does not exist."
-    echo "MusicPlayerPlus installation incomplete"
-    exit 1
-}
-[ -f ${CONFDIR}/bindings ] || {
-    echo "${CONFDIR}/bindings does not exist."
-    echo "MusicPlayerPlus installation incomplete"
-    exit 1
-}
-
-if [ -f ${HOME}/.config/mpcplus/config ]
-then
-  MPCDIR=".config/mpcplus"
-else
-  if [ -f ${HOME}/.mpcplus/config ]
-  then
-    MPCDIR=".mpcplus"
-  else
-    [ -d ${HOME}/.config/mpcplus ] || mkdir -p ${HOME}/.config/mpcplus
-    cp ${CONFDIR}/config ${HOME}/.config/mpcplus/config
-    MPCDIR=".config/mpcplus"
-  fi
-fi
-[ -f ${HOME}/${MPCDIR}/bindings ] || {
-  cp ${CONFDIR}/bindings ${HOME}/${MPCDIR}/bindings
-}
-
-for cfg in ${CFGS}
-do
-  [ -f ${HOME}/${MPCDIR}/${cfg} ] || {
-    cp ${CONFDIR}/${cfg} ${HOME}/${MPCDIR}/${cfg}
-    chmod 644 ${HOME}/${MPCDIR}/${cfg}
-  }
-done
-for scp in ${SCPS}
-do
-  [ -f ${HOME}/${MPCDIR}/${scp} ] || {
-    cp ${SCPTDIR}/${scp} ${HOME}/${MPCDIR}/${scp}
-    chmod 755 ${HOME}/${MPCDIR}/${scp}
-  }
-done
-
-[ -d ${HOME}/.config/mppcava ] || mkdir -p ${HOME}/.config/mppcava
-[ -f ${HOME}/.config/mppcava/config ] || {
-  cp ${MPPCDIR}/mppcava/config ${HOME}/.config/mppcava/config
-}
-[ -f ${HOME}/.config/mppcava/config-tmux ] || {
-  cp ${MPPCDIR}/mppcava/config-tmux ${HOME}/.config/mppcava/config-tmux
-}
-
-if [ -d ${HOME}/.config/tmuxp ]
-then
-  for tmc in ${MPPCDIR}/tmuxp/*
-  do
-    tmcbase=`basename "${tmc}"`
-    if [ -d "${tmc}" ]
-    then
-      [ -d "${HOME}/.config/tmuxp/${tmcbase}" ] || {
-        cp -a "${tmc}" "${HOME}/.config/tmuxp/${tmcbase}"
-      }
-    else
-      [ -f "${HOME}/.config/tmuxp/${tmcbase}" ] || {
-        cp "${tmc}" "${HOME}/.config/tmuxp/${tmcbase}"
-      }
-    fi
-  done
-else
-  cp -a ${MPPCDIR}/tmuxp ${HOME}/.config/tmuxp
-fi
 
 create_new_profile() {
   local proterm="$1"
@@ -155,6 +88,192 @@ create_new_profile() {
   dconf write $profile_path/font "'Monospace ${profont}'" 2> /dev/null
 }
 
+sync_music_dir() {
+  mpd_music=`grep ^music_directory ${MPDCONF}`
+  [ "${mpd_music}" ] || mpd_music=`grep \#music_directory ${MPDCONF}`
+  mpd_music=`echo ${mpd_music} | awk ' { print $2 } ' | sed -e "s/\"//g"`
+  # Need to expand the tilda to $HOME
+  exp_music="${mpd_music/#\~/$HOME}"
+  if [ "${mpd_music}" ]
+  then
+    # Create mpd_music directory if it does not exist
+    [ -d "${exp_music}" ] || mkdir -p ${exp_music}
+    mpc_custom=1
+    mpc_music=`grep ^mpd_music_dir ${HOME}/${MPCDIR}/config`
+    [ "${mpc_music}" ] || {
+      mpc_music=`grep \#mpd_music_dir ${HOME}/${MPCDIR}/config`
+      mpc_custom=
+    }
+    mpc_music=`echo ${mpc_music} | awk ' { print $3 } '`
+    [ "${mpd_music}" == "${mpc_music}" ] || {
+      if [ "${mpc_custom}" ]
+      then
+        cat ${HOME}/${MPCDIR}/config | sed -e "s%^mpd_music_dir.*%mpd_music_dir = ${mpd_music}%" > /tmp/mpc$$
+      else
+        cat ${HOME}/${MPCDIR}/config | sed -e "s%#mpd_music_dir.*%mpd_music_dir = ${mpd_music}%" > /tmp/mpc$$
+      fi
+      cp /tmp/mpc$$ ${HOME}/${MPCDIR}/config
+      rm -f /tmp/mpc$$
+      cat ${HOME}/${MPCDIR}/config-art.conf | sed -e "s%^mpd_music_dir.*%mpd_music_dir = ${mpd_music}%" > /tmp/art$$
+      cp /tmp/art$$ ${HOME}/${MPCDIR}/config-art.conf
+      rm -f /tmp/art$$
+    }
+    bts_custom=1
+    bts_music=`grep ^directory: ${BEETSCONF}`
+    [ "${bts_music}" ] || {
+      bts_music=`grep \#directory: ${BEETSCONF}`
+      bts_custom=
+    }
+    bts_music=`echo ${bts_music} | awk ' { print $2 } '`
+    [ "${mpd_music}" == "${bts_music}" ] || {
+      if [ "${bts_custom}" ]
+      then
+        cat ${BEETSCONF} | sed -e "s%^directory:.*%directory: ${mpd_music}%" > /tmp/bts$$
+      else
+        cat ${BEETSCONF} | sed -e "s%#directory:.*%directory: ${mpd_music}%" > /tmp/bts$$
+      fi
+      cp /tmp/bts$$ ${BEETSCONF}
+      rm -f /tmp/bts$$
+    }
+    have_beet=`type -p beet`
+    if [ "${have_beet}" ]
+    then
+      rm -f ${BEETSCONFDIR}/library.db
+      beet import -q ${exp_music} > /dev/null 2>&1 &
+    else
+      if [ -x ${HOME}/.local/bin/beet ]
+      then
+        rm -f ${BEETSCONFDIR}/library.db
+        ${HOME}/.local/bin/beet import -q ${exp_music} > /dev/null 2>&1 &
+      else
+        echo "WARNING: Cannot locate 'beet' executable"
+        echo "Music library ${exp_music} not imported to beets media organizer"
+      fi
+    fi
+
+    # Disable and stop any system-wide MPD service
+    systemctl is-enabled --quiet mpd.service
+    [ $? -eq 0 ] && sudo systemctl disable --quiet mpd.service
+    systemctl is-enabled --quiet mpd.socket
+    [ $? -eq 0 ] && sudo systemctl disable --quiet mpd.socket
+    systemctl is-active --quiet mpd.service
+    [ $? -eq 0 ] && sudo systemctl stop --quiet mpd.service
+    systemctl is-active --quiet mpd.socket
+    [ $? -eq 0 ] && sudo systemctl stop --quiet mpd.socket
+
+    systemctl --user daemon-reload --quiet
+    # Enable and activate the MPD user service
+    systemctl --user is-active --quiet mpd.service
+    if [ $? -eq 0 ]
+    then
+      # User service is active, restart to pickup any config changes
+      systemctl --user restart --quiet mpd.service
+    else
+      systemctl --user start --quiet mpd.service
+    fi
+    systemctl --user is-enabled --quiet mpd.service
+    [ $? -eq 0 ] || systemctl --user enable --quiet mpd.service
+    have_mpc=`type -p mpc`
+    [ "${have_mpc}" ] && mpc update --quiet
+
+    # Enable and activate the MPDstats user service
+    systemctl --user is-active --quiet mpdstats.service
+    if [ $? -eq 0 ]
+    then
+      # User service is active, restart to pickup any config changes
+      systemctl --user restart --quiet mpdstats.service
+    else
+      systemctl --user start --quiet mpdstats.service
+    fi
+    systemctl --user is-enabled --quiet mpdstats.service
+    [ $? -eq 0 ] || systemctl --user enable --quiet mpdstats.service
+  else
+    echo "WARNING:"
+    echo "Could not detect any music_directory setting in ${MPDCONF}"
+    echo "Manual configuration of ${MPDCONF} and ${HOME}/${MPCDIR}/config required"
+  fi
+}
+
+[ -f ${CONFDIR}/config ] || {
+    echo "${CONFDIR}/config does not exist."
+    echo "MusicPlayerPlus installation incomplete"
+    exit 1
+}
+[ -f ${CONFDIR}/bindings ] || {
+    echo "${CONFDIR}/bindings does not exist."
+    echo "MusicPlayerPlus installation incomplete"
+    exit 1
+}
+
+if [ -f ${HOME}/.config/mpcplus/config ]
+then
+  MPCDIR=".config/mpcplus"
+else
+  if [ -f ${HOME}/.mpcplus/config ]
+  then
+    MPCDIR=".mpcplus"
+  else
+    [ -d ${HOME}/.config/mpcplus ] || mkdir -p ${HOME}/.config/mpcplus
+    cp ${CONFDIR}/config ${HOME}/.config/mpcplus/config
+    MPCDIR=".config/mpcplus"
+  fi
+fi
+
+[ "$1" == "sync" ] && {
+  printf "\n\nSyncing MusicPlayerPlus music directory, please wait ..."
+  sync_music_dir
+  printf "\n\nMusicPlayerPlus music directory synchronized."
+  exit 0
+}
+
+printf "\n\nInitializing MusicPlayerPlus, please wait ..."
+[ -f ${HOME}/${MPCDIR}/bindings ] || {
+  cp ${CONFDIR}/bindings ${HOME}/${MPCDIR}/bindings
+}
+
+for cfg in ${CFGS}
+do
+  [ -f ${HOME}/${MPCDIR}/${cfg} ] || {
+    cp ${CONFDIR}/${cfg} ${HOME}/${MPCDIR}/${cfg}
+    chmod 644 ${HOME}/${MPCDIR}/${cfg}
+  }
+done
+for scp in ${SCPS}
+do
+  [ -f ${HOME}/${MPCDIR}/${scp} ] || {
+    cp ${SCPTDIR}/${scp} ${HOME}/${MPCDIR}/${scp}
+    chmod 755 ${HOME}/${MPCDIR}/${scp}
+  }
+done
+
+[ -d ${HOME}/.config/mppcava ] || mkdir -p ${HOME}/.config/mppcava
+[ -f ${HOME}/.config/mppcava/config ] || {
+  cp ${MPPCDIR}/mppcava/config ${HOME}/.config/mppcava/config
+}
+[ -f ${HOME}/.config/mppcava/config-tmux ] || {
+  cp ${MPPCDIR}/mppcava/config-tmux ${HOME}/.config/mppcava/config-tmux
+}
+
+if [ -d ${HOME}/.config/tmuxp ]
+then
+  for tmc in ${MPPCDIR}/tmuxp/*
+  do
+    tmcbase=`basename "${tmc}"`
+    if [ -d "${tmc}" ]
+    then
+      [ -d "${HOME}/.config/tmuxp/${tmcbase}" ] || {
+        cp -a "${tmc}" "${HOME}/.config/tmuxp/${tmcbase}"
+      }
+    else
+      [ -f "${HOME}/.config/tmuxp/${tmcbase}" ] || {
+        cp "${tmc}" "${HOME}/.config/tmuxp/${tmcbase}"
+      }
+    fi
+  done
+else
+  cp -a ${MPPCDIR}/tmuxp ${HOME}/.config/tmuxp
+fi
+
 # If no MusicPlayerPlus and Visualizer terminal profiles exist, create them
 declare -a profiles
 dconfdir=/org/gnome/terminal/legacy/profiles:
@@ -212,8 +331,6 @@ done
 # If there is no user MPD config
 # then copy the MusicPlayerPlus MPD config folder
 # into the user's home and setup user MPD service
-MPDCONFDIR="${HOME}/.config/mpd"
-MPDCONF="${MPDCONFDIR}/mpd.conf"
 [ -f ${MPDCONF} ] || {
   if [ -d ${MPDCONFDIR} ]
   then
@@ -223,8 +340,22 @@ MPDCONF="${MPDCONFDIR}/mpd.conf"
   fi
 }
 
+# If there is no user beets config
+# then copy the MusicPlayerPlus beets config folder
+# into the user's home and setup user mpdstats service
+[ -f ${BEETSCONF} ] || {
+  [ -d ${BEETSCONFDIR} ] || mkdir -p ${BEETSCONFDIR}
+  cp ${MPPCDIR}/beets/config.yaml ${BEETSCONF}
+}
+SYSTEMDIR="${HOME}/.config/systemd/user"
+MPDSTATSD="${SYSTEMDIR}/mpdstats.service"
+[ -f ${MPDSTATSD} ] || {
+  [ -d ${SYSTEMDIR} ] || mkdir -p ${SYSTEMDIR}
+  cp ${MPPCDIR}/beets/mpdstats.service ${MPDSTATSD}
+}
+
 CONF=${HOME}/.config
-FIFS="mppcava/config-tmux mppcava/config"
+FIFS="mppcava/config-tmux mppcava/config systemd/user/mpdstats.service"
 for cnf in ${FIFS}
 do
   [ -f ${CONF}/${cnf} ] || continue
@@ -232,72 +363,6 @@ do
   cp /tmp/cnf$$ ${CONF}/${cnf}
   rm -f /tmp/cnf$$
 done
-
-mpd_music=`grep ^music_directory ${MPDCONF}`
-[ "${mpd_music}" ] || mpd_music=`grep \#music_directory ${MPDCONF}`
-mpd_music=`echo ${mpd_music} | awk ' { print $2 } ' | sed -e "s/\"//g"`
-# Need to expand the tilda to $HOME
-exp_music="${mpd_music/#\~/$HOME}"
-if [ "${mpd_music}" ]
-then
-  # Create mpd_music directory if it does not exist
-  [ -d "${exp_music}" ] || {
-    if [ -d "${HOME}/Music" ]
-    then
-      ln -s ${HOME}/Music ${exp_music}
-    else
-      mkdir -p ${exp_music}
-    fi
-  }
-  mpc_custom=1
-  mpc_music=`grep ^mpd_music_dir ${HOME}/${MPCDIR}/config`
-  [ "${mpc_music}" ] || {
-    mpc_music=`grep \#mpd_music_dir ${HOME}/${MPCDIR}/config`
-    mpc_custom=
-  }
-  mpc_music=`echo ${mpc_music} | awk ' { print $3 } '`
-  [ "${mpd_music}" == "${mpc_music}" ] || {
-    if [ "${mpc_custom}" ]
-    then
-      cat ${HOME}/${MPCDIR}/config | sed -e "s%^mpd_music_dir.*%mpd_music_dir = ${mpd_music}%" > /tmp/newconf$$
-    else
-      cat ${HOME}/${MPCDIR}/config | sed -e "s%#mpd_music_dir.*%mpd_music_dir = ${mpd_music}%" > /tmp/newconf$$
-    fi
-    cp /tmp/newconf$$ ${HOME}/${MPCDIR}/config
-    rm -f /tmp/newconf$$
-    cat ${HOME}/${MPCDIR}/config-art.conf | sed -e "s%^mpd_music_dir.*%mpd_music_dir = ${mpd_music}%" > /tmp/config-art$$
-    cp /tmp/config-art$$ ${HOME}/${MPCDIR}/config-art.conf
-    rm -f /tmp/config-art$$
-  }
-
-  # Disable and stop any system-wide MPD service
-  systemctl is-enabled --quiet mpd.service
-  [ $? -eq 0 ] && sudo systemctl disable --quiet mpd.service
-  systemctl is-enabled --quiet mpd.socket
-  [ $? -eq 0 ] && sudo systemctl disable --quiet mpd.socket
-  systemctl is-active --quiet mpd.service
-  [ $? -eq 0 ] && sudo systemctl stop --quiet mpd.service
-  systemctl is-active --quiet mpd.socket
-  [ $? -eq 0 ] && sudo systemctl stop --quiet mpd.socket
-
-  # Enable and activate the MPD user service
-  systemctl --user is-active --quiet mpd.service
-  if [ $? -eq 0 ]
-  then
-    # User service is active, restart to pickup any config changes
-    systemctl --user restart --quiet mpd.service
-  else
-    systemctl --user start --quiet mpd.service
-  fi
-  systemctl --user is-enabled --quiet mpd.service
-  [ $? -eq 0 ] || systemctl --user enable --quiet mpd.service
-  have_mpc=`type -p mpc`
-  [ "${have_mpc}" ] && mpc update --quiet
-else
-  echo "WARNING:"
-  echo "Could not detect any music_directory setting in ${MPDCONF}"
-  echo "Manual configuration of ${MPDCONF} and ${HOME}/${MPCDIR}/config required"
-fi
 
 # Setup default tmux configuration for this user
 [ -f ${MPPCDIR}/tmux.conf ] && {
@@ -372,10 +437,29 @@ fi
   fi
 }
 
+TPM="${HOME}/.tmux/plugins/tpm"
+
+[ -d ${TPM} ] || {
+  have_git=`type -p git`
+  [ "${have_git}" ] && {
+    git clone https://github.com/tmux-plugins/tpm ${TPM} > /dev/null 2>&1
+  }
+}
+
+[ -d ${TPM} ] && {
+  grep plugins/tpm/tpm ${HOME}/.tmux.conf > /dev/null || {
+    [ -f ${MPPCDIR}/tmux-tpm.conf ] && {
+      cat ${MPPCDIR}/tmux-tpm.conf >> ${HOME}/.tmux.conf
+      [ -x ${TPM}/bin/install_plugins ] && ${TPM}/bin/install_plugins > /dev/null 2>&1
+    }
+  }
+}
+
 have_pip=`type -p pip`
 if [ "${have_pip}" ]
 then
-  for pkg in asciimatics sacad tmuxp ueberzug
+  for pkg in asciimatics beautifulsoup4 beets pylast \
+             python-mpd2 requests sacad tmuxp ueberzug
   do
     if pip list | grep ${pkg} > /dev/null
     then
@@ -385,6 +469,7 @@ then
     fi
   done
 else
+  echo ""
   echo "WARNING: Python pip module not found."
   echo "Pip is required to install several MusicPlayerPlus components."
   echo ""
@@ -396,6 +481,8 @@ else
   echo "After verifying that pip is installed,"
   echo "rerun the 'mpcinit' MusicPlayer initialization."
 fi
+
+sync_music_dir
 
 printf "\nMusicPlayerPlus Initialization Complete\n"
 printf "\nVisit the MusicPlayerPlus Wiki at:"
