Improve mppdl, handle multiple file downloads, name downloads with title

diff --git a/bin/mppdl b/bin/mppdl
--- a/bin/mppdl
+++ b/bin/mppdl
@@ -17,13 +17,15 @@ TRACK=
 
 usage() {
   printf "\nUsage: mppdl [-a album] [-A artist] [-i] [-f fmt] [-l]"
-  printf "\n             [-t track] [-T title] bandcamp|soundcloud|URL"
+  printf "\n             [-p playlist] [-t track] [-T title]"
+  printf "\n             bandcamp|soundcloud|URL"
   printf "\nWhere:"
-  printf "\n\t-a 'album' saves the download in the subdirectory 'album'"
+  printf "\n\t-a 'album' saves the downloads in the subdirectory 'album'"
   printf "\n\t-A 'artist' saves the download with filename"
   printf "\n\t\t'artist'-'title'.${FMT}"
   printf "\n\t-i indicates import audio into Beets after download completes"
   printf "\n\t-f 'fmt' saves the download in 'fmt' format (default m4a)"
+  printf "\n\t-p 'playlist' saves the downloads in the subdirectory 'playlist'"
   printf "\n\t-t 'track' saves the download with filename"
   printf "\n\t\t'track'-'artist'-'title'.${FMT}"
   printf "\n\t-T 'title' saves the download with filename"
@@ -37,7 +39,7 @@ usage() {
   exit 1
 }
 
-while getopts "a:A:f:t:T:ilu" flag; do
+while getopts "a:A:f:p:t:T:ilu" flag; do
     case $flag in
         a)
             ALBUM="$OPTARG"
@@ -59,6 +61,9 @@ while getopts "a:A:f:t:T:ilu" flag; do
             ;;
         l)
             LIST=1
+            ;;
+        p)
+            ALBUM="$OPTARG"
             ;;
         t)
             TRACK="$OPTARG"
@@ -131,115 +136,144 @@ if [ "${LIST}" ]
 then
   ${LISTCOMM} ${URL}
 else
-  DEST=`${COMMAND} ${URL} \
-                   -o "${DDIR}/%(id)s.%(ext)s" 2>&1 | \
-                   grep Destination | tail -1`
-  if [ "${DEST}" ]
-  then
-    FN=`echo ${DEST} | awk -F '/' ' { print $NF } ' | sed -e "s/'//g"`
-    EXT=`echo ${FN} | awk -F '.' ' { print $NF } '`
-    if [ "${ARTIST}" ]
+  surl=`echo "${URL}" | sed -e "s%https://%%" -e "s%http://%%"`
+  printf "\nDownloading:\n  ${surl}\n"
+  printf "\nStoring download(s) in:\n  ${DDIR}\n\n"
+  destinations=`${COMMAND} ${URL} \
+                   -o "${DDIR}/%(title)s.%(ext)s" 2>&1 | \
+                   grep Destination: | \
+                   awk -F '/' ' { print $NF } ' | sed -e "s/'//g"`
+  numdests=`echo "${destinations}" | wc -l`
+  [ ${numdests} -gt 1 ] && {
+    [ "${TRACK}" ] || TRACK=1
+  }
+  while IFS= read -r FN
+  do
+    echo "Processing ${FN}"
+    if [ "${FN}" ]
     then
-      if [ "${TITLE}" ]
+      [ -f "${DDIR}/${FN}" ] || {
+        echo "${DDIR}/${FN} does not exist. Skipping."
+        continue
+      }
+      EXT=`echo ${FN} | awk -F '.' ' { print $NF } '`
+      if [ "${ARTIST}" ]
       then
-        if [ "${TRACK}" ]
+        if [ "${TITLE}" ]
         then
-          if [ -f "${DDIR}/${TRACK}-${ARTIST}-${TITLE}.${EXT}" ]
+          if [ "${TRACK}" ]
           then
-            mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}-${TITLE}-$$.${EXT}"
-            FN="${TRACK}-${ARTIST}-${TITLE}-$$.${EXT}"
+            if [ -f "${DDIR}/${TRACK}-${ARTIST}-${TITLE}.${EXT}" ]
+            then
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}-${TITLE}-$$.${EXT}"
+              FN="${TRACK}-${ARTIST}-${TITLE}-$$.${EXT}"
+            else
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}-${TITLE}.${EXT}"
+              FN="${TRACK}-${ARTIST}-${TITLE}.${EXT}"
+            fi
+            TRACK=$((TRACK + 1))
           else
-            mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}-${TITLE}.${EXT}"
-            FN="${TRACK}-${ARTIST}-${TITLE}.${EXT}"
+            if [ -f "${DDIR}/${ARTIST}-${TITLE}.${EXT}" ]
+            then
+              mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}-${TITLE}-$$.${EXT}"
+              FN="${ARTIST}-${TITLE}-$$.${EXT}"
+            else
+              mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}-${TITLE}.${EXT}"
+              FN="${ARTIST}-${TITLE}.${EXT}"
+            fi
           fi
         else
-          if [ -f "${DDIR}/${ARTIST}-${TITLE}.${EXT}" ]
+          if [ "${TRACK}" ]
           then
-            mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}-${TITLE}-$$.${EXT}"
-            FN="${ARTIST}-${TITLE}-$$.${EXT}"
+            if [ -f "${DDIR}/${TRACK}-${ARTIST}.${EXT}" ]
+            then
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}-$$.${EXT}"
+              FN="${TRACK}-${ARTIST}-$$.${EXT}"
+            else
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}.${EXT}"
+              FN="${TRACK}-${ARTIST}.${EXT}"
+            fi
+            TRACK=$((TRACK + 1))
           else
-            mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}-${TITLE}.${EXT}"
-            FN="${ARTIST}-${TITLE}.${EXT}"
+            if [ -f "${DDIR}/${TRACK}-${ARTIST}.${EXT}" ]
+            then
+              mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}-$$.${EXT}"
+              FN="${ARTIST}-$$.${EXT}"
+            else
+              mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}.${EXT}"
+              FN="${ARTIST}.${EXT}"
+            fi
           fi
         fi
       else
-        if [ "${TRACK}" ]
+        if [ "${TITLE}" ]
         then
-          if [ -f "${DDIR}/${TRACK}-${ARTIST}.${EXT}" ]
+          if [ "${TRACK}" ]
           then
-            mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}-$$.${EXT}"
-            FN="${TRACK}-${ARTIST}-$$.${EXT}"
+            if [ -f "${DDIR}/${TRACK}-${TITLE}.${EXT}" ]
+            then
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${TITLE}-$$.${EXT}"
+              FN="${TRACK}-${TITLE}-$$.${EXT}"
+            else
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${TITLE}.${EXT}"
+              FN="${TRACK}-${TITLE}.${EXT}"
+            fi
+            TRACK=$((TRACK + 1))
           else
-            mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${ARTIST}.${EXT}"
-            FN="${TRACK}-${ARTIST}.${EXT}"
+            if [ -f "${DDIR}/${TITLE}.${EXT}" ]
+            then
+              mv "${DDIR}/${FN}" "${DDIR}/${TITLE}-$$.${EXT}"
+              FN="${TITLE}-$$.${EXT}"
+            else
+              mv "${DDIR}/${FN}" "${DDIR}/${TITLE}.${EXT}"
+              FN="${TITLE}.${EXT}"
+            fi
           fi
         else
-          if [ -f "${DDIR}/${TRACK}-${ARTIST}.${EXT}" ]
-          then
-            mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}-$$.${EXT}"
-            FN="${ARTIST}-$$.${EXT}"
-          else
-            mv "${DDIR}/${FN}" "${DDIR}/${ARTIST}.${EXT}"
-            FN="${ARTIST}.${EXT}"
-          fi
+          [ "${TRACK}" ] && {
+            if [ -f "${DDIR}/${TRACK}-${FN}" ]
+            then
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}$$-${FN}"
+              FN="${TRACK}$$-${FN}"
+            else
+              mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${FN}"
+              FN="${TRACK}-${FN}"
+            fi
+            TRACK=$((TRACK + 1))
+          }
         fi
       fi
-    else
-      [ "${TITLE}" ] && {
-        if [ "${TRACK}" ]
-        then
-          if [ -f "${DDIR}/${TRACK}-${TITLE}.${EXT}" ]
+      if [ "${EXT}" == "${FMT}" ]
+      then
+        [ "${IMPORT}" ] && {
+          if [ "${ALBUM}" ]
           then
-            mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${TITLE}-$$.${EXT}"
-            FN="${TRACK}-${TITLE}-$$.${EXT}"
+            [ -d "${DDIR}" ] && beet import -q "${DDIR}"
+            [ -d "${DDIR}" ] && beet import -q -s "${DDIR}"
           else
-            mv "${DDIR}/${FN}" "${DDIR}/${TRACK}-${TITLE}.${EXT}"
-            FN="${TRACK}-${TITLE}.${EXT}"
+            beet import -q -s "${DDIR}/${FN}"
           fi
-        else
-          if [ -f "${DDIR}/${TITLE}.${EXT}" ]
+        }
+      else
+        NAME=`echo ${FN} | awk 'BEGIN{FS=OFS="."}{NF--; print}'`
+        echo "Converting ${DDIR}/${FN} to ${NAME}.${FMT}"
+        ffmpeg -i "${DDIR}/${FN}" \
+               -vn "${DDIR}/${NAME}.${FMT}"
+        echo "Removing ${DDIR}/${FN}"
+        rm -f "${DDIR}/${FN}"
+        [ "${IMPORT}" ] && {
+          if [ "${ALBUM}" ]
           then
-            mv "${DDIR}/${FN}" "${DDIR}/${TITLE}-$$.${EXT}"
-            FN="${TITLE}-$$.${EXT}"
+            [ -d "${DDIR}" ] && beet import -q "${DDIR}"
+            [ -d "${DDIR}" ] && beet import -q -s "${DDIR}"
           else
-            mv "${DDIR}/${FN}" "${DDIR}/${TITLE}.${EXT}"
-            FN="${TITLE}.${EXT}"
+            beet import -q -s "${DDIR}/${NAME}.${FMT}"
           fi
-        fi
-      }
-    fi
-    if [ "${EXT}" == "${FMT}" ]
-    then
-      echo "Download: ${DDIR}/${FN}"
-      [ "${IMPORT}" ] && {
-        if [ "${ALBUM}" ]
-        then
-          [ -d "${DDIR}" ] && beet import -q "${DDIR}"
-          [ -d "${DDIR}" ] && beet import -q -s "${DDIR}"
-        else
-          beet import -q -s "${DDIR}/${FN}"
-        fi
-      }
+        }
+      fi
     else
-      NAME=`echo ${FN} | awk 'BEGIN{FS=OFS="."}{NF--; print}'`
-      echo "Converting ${DDIR}/${FN} to ${NAME}.${FMT}"
-      ffmpeg -i "${DDIR}/${FN}" \
-             -vn "${DDIR}/${NAME}.${FMT}"
-      echo "Removing ${DDIR}/${FN}"
-      rm -f "${DDIR}/${FN}"
-      echo "Download: ${DDIR}/${NAME}.${FMT}"
-      [ "${IMPORT}" ] && {
-        if [ "${ALBUM}" ]
-        then
-          [ -d "${DDIR}" ] && beet import -q "${DDIR}"
-          [ -d "${DDIR}" ] && beet import -q -s "${DDIR}"
-        else
-          beet import -q -s "${DDIR}/${NAME}.${FMT}"
-        fi
-      }
+      echo "Could not determine destination filename in ${DDIR}/"
     fi
-  else
-    echo "Could not determine destination filename in ${DDIR}/"
-  fi
+  done < <(printf '%s\n' "${destinations}")
 fi
 
