Finishing touches on PKGBUILD, add -G flag to mpplus for M4A conversion, reorder service menu

diff --git a/bin/mpplus b/bin/mpplus
--- a/bin/mpplus
+++ b/bin/mpplus
@@ -52,7 +52,7 @@ SCRIPTS="${MPP_DIR}/scripts"
 BEETSLOGDIR="${HOME}/.config/beets/logs"
 
 usage() {
-  printf "\nUsage: mpplus [-A] [-a] [-b] [-B] [-C client] [-g] [-F] [-f]"
+  printf "\nUsage: mpplus [-A] [-a] [-b] [-B] [-C client] [-F] [-f] [-G] [-g]"
   printf "\n\t[-D art|bandcamp|soundcloud] [-d music_directory] [-h] [-I]"
   printf "\n\t[-i] [-jJ] [-k] [-L] [-m] [-n num] [-N]"
   printf "\n\t[-M alsaconf|enable|disable|restart|start|stop|status]"
@@ -91,7 +91,10 @@ usage() {
   printf "\n\t-d 'music_directory' specifies the music directory to use for"
   printf "\n\t\tdownloaded album cover art (without this option -D will use"
   printf "\n\t\tthe 'music_directory' setting in '~/.config/mpd/mpd.conf'"
-  printf "\n\t-F indicates convert WAV/M4A format files in the music library"
+  printf "\n\t-F indicates convert WAV format files in the music library"
+  printf "\n\t\tto MP3 format files and exit. A subsequent 'mpplus -I' import"
+  printf "\n\t\twill be necessary to import these newly converted music files."
+  printf "\n\t-G indicates convert M4A format files in the music library"
   printf "\n\t\tto MP3 format files and exit. A subsequent 'mpplus -I' import"
   printf "\n\t\twill be necessary to import these newly converted music files."
   printf "\n\t-I indicates import albums and songs from 'music_directory' to beets and exit"
@@ -170,6 +173,25 @@ kill_tmux_sessions() {
 }
 
 make_it_so() {
+  [ "${CONVERT_M4A}" ] && {
+    if [ -x ${SCRIPTS}/m4a2mp3.sh ]
+    then
+      printf "\nConverting M4A files\n"
+      if [ "${MUSIC_DIRECTORY}" ]
+      then
+        ${SCRIPTS}/m4a2mp3.sh -d "${MUSIC_DIRECTORY}"
+      else
+        ${SCRIPTS}/m4a2mp3.sh
+      fi
+    else
+      echo "${SCRIPTS}/m4a2mp3.sh not found or not executable"
+      echo "Check your MusicPlayerPlus installation"
+      echo ""
+      echo "Manual media file conversion may be required"
+    fi
+    [ "${DO_NOT_EXIT}" ] || exit 0
+    return
+  }
   [ "${CONVERT_WAV}" ] && {
     if [ -x ${SCRIPTS}/wav2mp3.sh ]
     then
@@ -182,21 +204,6 @@ make_it_so() {
       fi
     else
       echo "${SCRIPTS}/wav2mp3.sh not found or not executable"
-      echo "Check your MusicPlayerPlus installation"
-      echo ""
-      echo "Manual media file conversion may be required"
-    fi
-    if [ -x ${SCRIPTS}/m4a2mp3.sh ]
-    then
-      printf "\nConverting M4A files\n"
-      if [ "${MUSIC_DIRECTORY}" ]
-      then
-        ${SCRIPTS}/m4a2mp3.sh -d "${MUSIC_DIRECTORY}"
-      else
-        ${SCRIPTS}/m4a2mp3.sh
-      fi
-    else
-      echo "${SCRIPTS}/m4a2mp3.sh not found or not executable"
       echo "Check your MusicPlayerPlus installation"
       echo ""
       echo "Manual media file conversion may be required"
@@ -1247,50 +1254,26 @@ show_services_menu() {
     fi
     printf "\nCurrent status of MusicPlayerPlus Services:"
     printf "\n\tMusic Player Daemon service is ${m_enabled} and ${m_active}"
-    printf "\n\tMusic Player Last.fm Scrobbler service is ${y_enabled} and ${y_active}"
     printf "\n\tBeets MPD Stats service is ${s_enabled} and ${s_active}"
     printf "\n\tBeets Web service is ${w_enabled} and ${w_active}"
-    printf "\n\tMopidy Music Server is ${z_inst}, ${z_enabled} and ${z_active}"
-    printf "\n\tNavidrome Music Server is ${n_inst}, ${n_enabled} and ${n_active}\n\n"
+    printf "\n\tLast.fm Scrobbler service is ${y_enabled} and ${y_active}"
+    printf "\n\tMopidy Server is ${z_inst}, ${z_enabled} and ${z_active}"
+    printf "\n\tNavidrome Server is ${n_inst}, ${n_enabled} and ${n_active}\n\n"
     PS3="${BOLD}${PLEASE} command choice (numeric or text, 'h' for help): ${NORM}"
     options=("Configure ALSA Sound System")
-    if [ "${have_mopidy}" ]
+    [ "${have_mopidy}" ] || options+=("Install Mopidy Server")
+    [ "${have_navi}" ] || options+=("Install Navidrome Server")
+    if [ "${w_enabled}" == "enabled" ]
     then
-      if [ "${z_enabled}" == "enabled" ]
-      then
-        options+=("Disable Mopidy Music Server")
-      else
-        options+=("Enable Mopidy Music Server")
-      fi
-      if [ "${z_active}" == "active" ]
-      then
-        options+=("Stop Mopidy Music Server")
-        options+=("Restart Mopidy Music Server")
-      else
-        options+=("Start Mopidy Music Server")
-      fi
-      options+=("Status of Mopidy Music Server")
+      options+=("Disable Beets Web Service")
     else
-      options+=("Install Mopidy Music Server")
+      options+=("Enable Beets Web Service")
     fi
-    if [ "${have_navi}" ]
+    if [ "${s_enabled}" == "enabled" ]
     then
-      if [ "${n_enabled}" == "enabled" ]
-      then
-        options+=("Disable Navidrome Music Server")
-      else
-        options+=("Enable Navidrome Music Server")
-      fi
-      if [ "${n_active}" == "active" ]
-      then
-        options+=("Stop Navidrome Music Server")
-        options+=("Restart Navidrome Music Server")
-      else
-        options+=("Start Navidrome Music Server")
-      fi
-      options+=("Status of Navidrome Music Server")
+      options+=("Disable Beets MPD Stats")
     else
-      options+=("Install Navidrome Music Server")
+      options+=("Enable Beets MPD Stats")
     fi
     if [ "${m_enabled}" == "enabled" ]
     then
@@ -1298,19 +1281,27 @@ show_services_menu() {
     else
       options+=("Enable Music Player Daemon")
     fi
-    if [ "${m_active}" == "active" ]
+    [ "${have_mopidy}" ] && {
+      if [ "${z_enabled}" == "enabled" ]
+      then
+        options+=("Disable Mopidy Server")
+      else
+        options+=("Enable Mopidy Server")
+      fi
+    }
+    [ "${have_navi}" ] && {
+      if [ "${n_enabled}" == "enabled" ]
+      then
+        options+=("Disable Navidrome Server")
+      else
+        options+=("Enable Navidrome Server")
+      fi
+    }
+    if [ "${y_enabled}" == "enabled" ]
     then
-      options+=("Stop Music Player Daemon")
-      options+=("Restart Music Player Daemon")
+      options+=("Disable Last.FM Scrobbler")
     else
-      options+=("Start Music Player Daemon")
-    fi
-    options+=("Status of Music Player Daemon")
-    if [ "${s_enabled}" == "enabled" ]
-    then
-      options+=("Disable Beets MPD Stats")
-    else
-      options+=("Enable Beets MPD Stats")
+      options+=("Enable Last.FM Scrobbler")
     fi
     if [ "${s_active}" == "active" ]
     then
@@ -1319,13 +1310,6 @@ show_services_menu() {
     else
       options+=("Start Beets MPD Stats")
     fi
-    options+=("Status of Beets MPD Stats")
-    if [ "${w_enabled}" == "enabled" ]
-    then
-      options+=("Disable Beets Web Service")
-    else
-      options+=("Enable Beets Web Service")
-    fi
     if [ "${w_active}" == "active" ]
     then
       options+=("Stop Beets Web Service")
@@ -1333,21 +1317,44 @@ show_services_menu() {
     else
       options+=("Start Beets Web Service")
     fi
-    options+=("Status of Beets Web Service")
-    if [ "${y_enabled}" == "enabled" ]
+    if [ "${m_active}" == "active" ]
     then
-      options+=("Disable Music Player Scrobbler")
+      options+=("Stop Music Player Daemon")
+      options+=("Restart Music Player Daemon")
     else
-      options+=("Enable Music Player Scrobbler")
+      options+=("Start Music Player Daemon")
     fi
+    [ "${have_mopidy}" ] && {
+      if [ "${z_active}" == "active" ]
+      then
+        options+=("Stop Mopidy Server")
+        options+=("Restart Mopidy Server")
+      else
+        options+=("Start Mopidy Server")
+      fi
+    }
+    [ "${have_navi}" ] && {
+      if [ "${n_active}" == "active" ]
+      then
+        options+=("Stop Navidrome Server")
+        options+=("Restart Navidrome Server")
+      else
+        options+=("Start Navidrome Server")
+      fi
+    }
     if [ "${y_active}" == "active" ]
     then
-      options+=("Stop Music Player Scrobbler")
-      options+=("Restart Music Player Scrobbler")
+      options+=("Stop Last.FM Scrobbler")
+      options+=("Restart Last.FM Scrobbler")
     else
-      options+=("Start Music Player Scrobbler")
+      options+=("Start Last.FM Scrobbler")
     fi
-    options+=("Status of Music Player Scrobbler")
+    options+=("Status of Music Player Daemon")
+    options+=("Status of Beets MPD Stats")
+    options+=("Status of Beets Web Service")
+    [ "${have_mopidy}" ] && options+=("Status of Mopidy Server")
+    [ "${have_navi}" ] && options+=("Status of Navidrome Server")
+    options+=("Status of Last.FM Scrobbler")
     options+=("Main menu" "Quit")
     select opt in "${options[@]}"
     do
@@ -1367,12 +1374,12 @@ show_services_menu() {
               mpp_service alsaconf
               break
               ;;
-          "Install Mopidy Music Server",*|*,"Install Mopidy Music Server")
+          "Install Mopidy Server",*|*,"Install Mopidy Server")
               mppinit mopidy
               have_mopidy=`type -p mopidy`
               break
               ;;
-          "Enable Mopidy Music Server",*|*,"Enable Mopidy Music Server")
+          "Enable Mopidy Server",*|*,"Enable Mopidy Server")
               mpp_service disable mpdstats
               mpp_service stop mpdstats
               mpp_service disable yams
@@ -1382,11 +1389,11 @@ show_services_menu() {
               mpp_service enable mopidy
               break
               ;;
-          "Disable Mopidy Music Server",*|*,"Disable Mopidy Music Server")
+          "Disable Mopidy Server",*|*,"Disable Mopidy Server")
               mpp_service disable mopidy
               break
               ;;
-          "Start Mopidy Music Server",*|*,"Start Mopidy Music Server")
+          "Start Mopidy Server",*|*,"Start Mopidy Server")
               mpp_service disable mpdstats
               mpp_service stop mpdstats
               mpp_service disable yams
@@ -1396,11 +1403,11 @@ show_services_menu() {
               mpp_service start mopidy
               break
               ;;
-          "Stop Mopidy Music Server",*|*,"Stop Mopidy Music Server")
+          "Stop Mopidy Server",*|*,"Stop Mopidy Server")
               mpp_service stop mopidy
               break
               ;;
-          "Restart Mopidy Music Server",*|*,"Restart Mopidy Music Server")
+          "Restart Mopidy Server",*|*,"Restart Mopidy Server")
               mpp_service disable mpdstats
               mpp_service stop mpdstats
               mpp_service disable yams
@@ -1410,11 +1417,11 @@ show_services_menu() {
               mpp_service restart mopidy
               break
               ;;
-          "Status of Mopidy Music Server",*|*,"Status of Mopidy Music Server")
+          "Status of Mopidy Server",*|*,"Status of Mopidy Server")
               mpp_service status mopidy
               break
               ;;
-          "Install Navidrome Music Server",*|*,"Install Navidrome Music Server")
+          "Install Navidrome Server",*|*,"Install Navidrome Server")
               mppinit navidrome
               if [ -x /opt/navidrome/navidrome ]
               then
@@ -1424,27 +1431,27 @@ show_services_menu() {
               fi
               break
               ;;
-          "Enable Navidrome Music Server",*|*,"Enable Navidrome Music Server")
+          "Enable Navidrome Server",*|*,"Enable Navidrome Server")
               mpp_service enable navidrome
               break
               ;;
-          "Disable Navidrome Music Server",*|*,"Disable Navidrome Music Server")
+          "Disable Navidrome Server",*|*,"Disable Navidrome Server")
               mpp_service disable navidrome
               break
               ;;
-          "Start Navidrome Music Server",*|*,"Start Navidrome Music Server")
+          "Start Navidrome Server",*|*,"Start Navidrome Server")
               mpp_service start navidrome
               break
               ;;
-          "Stop Navidrome Music Server",*|*,"Stop Navidrome Music Server")
+          "Stop Navidrome Server",*|*,"Stop Navidrome Server")
               mpp_service stop navidrome
               break
               ;;
-          "Restart Navidrome Music Server",*|*,"Restart Navidrome Music Server")
+          "Restart Navidrome Server",*|*,"Restart Navidrome Server")
               mpp_service restart navidrome
               break
               ;;
-          "Status of Navidrome Music Server",*|*,"Status of Navidrome Music Server")
+          "Status of Navidrome Server",*|*,"Status of Navidrome Server")
               mpp_service status navidrome
               break
               ;;
@@ -1574,7 +1581,7 @@ show_services_menu() {
               mpp_service status webplugin
               break
               ;;
-          "Enable Music Player Scrobbler",*|*,"Enable Music Player Scrobbler")
+          "Enable Last.FM Scrobbler",*|*,"Enable Last.FM Scrobbler")
               [ "${have_mopidy}" ] && {
                 [ "${z_active}" == "active" ] || \
                 [ "${z_enabled}" == "enabled" ] && {
@@ -1586,11 +1593,11 @@ show_services_menu() {
               mpp_service enable yams
               break
               ;;
-          "Disable Music Player Scrobbler",*|*,"Disable Music Player Scrobbler")
+          "Disable Last.FM Scrobbler",*|*,"Disable Last.FM Scrobbler")
               mpp_service disable yams
               break
               ;;
-          "Start Music Player Scrobbler",*|*,"Start Music Player Scrobbler")
+          "Start Last.FM Scrobbler",*|*,"Start Last.FM Scrobbler")
               [ "${have_mopidy}" ] && {
                 [ "${z_active}" == "active" ] || \
                 [ "${z_enabled}" == "enabled" ] && {
@@ -1602,11 +1609,11 @@ show_services_menu() {
               mpp_service start yams
               break
               ;;
-          "Stop Music Player Scrobbler",*|*,"Stop Music Player Scrobbler")
+          "Stop Last.FM Scrobbler",*|*,"Stop Last.FM Scrobbler")
               mpp_service stop yams
               break
               ;;
-          "Restart Music Player Scrobbler",*|*,"Restart Music Player Scrobbler")
+          "Restart Last.FM Scrobbler",*|*,"Restart Last.FM Scrobbler")
               [ "${have_mopidy}" ] && {
                 [ "${z_active}" == "active" ] || \
                 [ "${z_enabled}" == "enabled" ] && {
@@ -1618,7 +1625,7 @@ show_services_menu() {
               mpp_service restart yams
               break
               ;;
-          "Status of Music Player Scrobbler",*|*,"Status of Music Player Scrobbler")
+          "Status of Last.FM Scrobbler",*|*,"Status of Last.FM Scrobbler")
               mpp_service status yams
               break
               ;;
@@ -1882,8 +1889,9 @@ show_main_menu() {
     [ "${have_retro}" ] && options+=("Retro Music Player Plus")
     [ "${have_tilix}" ] && options+=("Tilix Music Player Plus")
     [ "${have_cantata}" ] && options+=("Cantata Music Player Plus")
-    [ "${need_yams}" ] && options+=("Activate Last.fm Scrobbler Service")
-    options+=("ASCIImatics Animations" "Convert WAV/M4A files to MP3")
+    [ "${need_yams}" ] && options+=("Activate Last.fm Scrobbler")
+    options+=("ASCIImatics Animations")
+    options+=("Convert M4A files to MP3" "Convert WAV files to MP3")
     options+=("Import Music to Beets")
     options+=("Fetch Lyrics" "Blissify Audio Info Extraction")
     options+=("Essentia Audio Info Extraction")
@@ -1946,7 +1954,11 @@ show_main_menu() {
               skip_it_so=1
               break
               ;;
-          "Convert"*,*|*,"Convert"*)
+          "Convert M4A"*,*|*,"Convert M4A"*)
+              CONVERT_M4A=1
+              break
+              ;;
+          "Convert WAV"*,*|*,"Convert WAV"*)
               CONVERT_WAV=1
               break
               ;;
@@ -2041,6 +2053,7 @@ init_vars() {
   CLIENT=
   COVER_ART=
   CONVERT_WAV=
+  CONVERT_M4A=
   DOWNLOAD_ART=
   DOWNLOAD_BANDCAMP=
   DOWNLOAD_SOUNDCLOUD=
@@ -2156,7 +2169,7 @@ else
   use_figlet=
 fi
 
-while getopts "AabBC:D:d:FfghiIjJkLmM:n:NpP:qrRSs:tTv:wWx:X:yYz:u" flag; do
+while getopts "AabBC:D:d:FfGghiIjJkLmM:n:NpP:qrRSs:tTv:wWx:X:yYz:u" flag; do
   case $flag in
     a)
       AUDIO=1
@@ -2225,6 +2238,9 @@ while getopts "AabBC:D:d:FfghiIjJkLmM:n:NpP:qrRSs:tTv:wWx:X:yYz:u" flag; do
       ;;
     f)
       FULLSCREEN=1
+      ;;
+    G)
+      CONVERT_M4A=1
       ;;
     g)
       USE_GRAD=
