Move Arch package to filename format similar to Debian and RPM

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -12,8 +12,7 @@
 # sudo apt-get install -f
 
 SRC_NAME="MusicPlayerPlus"
-PKG_NAMES="MusicPlayerPlus"
-APT_NAMES="musicplayerplus"
+PKG_NAMES="MusicPlayerPlus musicplayerplus"
 SRC="${HOME}/src"
 DEB_ARCH=amd64
 RPM_ARCH=x86_64
@@ -70,149 +69,148 @@ install_selected() {
   PKG_SELECTED=`echo $PKG_SELECTED | sed -e "s/^ //"`
 }
 
-plat=`uname -s`
-if [ "$plat" == "Darwin" ]
-then
-  ./macInstall
-else
-  debian=
-  arch=
-  have_apt=`type -p apt`
-  have_dpkg=`type -p dpkg`
-  have_rpm=`type -p rpm`
-  have_yum=`type -p yum`
-  have_pac=`type -p pacman`
-  [ -f /etc/os-release ] && . /etc/os-release
-  [ "${ID_LIKE}" == "debian" ] && debian=1
-  [ "${ID}" == "arch" ] && arch=1
-  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
+debian=
+arch=
+have_apt=`type -p apt`
+have_dpkg=`type -p dpkg`
+have_rpm=`type -p rpm`
+have_yum=`type -p yum`
+have_pac=`type -p pacman`
+[ -f /etc/os-release ] && . /etc/os-release
+[ "${ID_LIKE}" == "debian" ] && debian=1
+[ "${ID}" == "arch" ] && arch=1
+[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
 
+if [ "${debian}" ]
+then
+  SUF=deb
+  [ "${have_dpkg}" ] && {
+    dpkg_arch=`dpkg --print-architecture`
+    [ "${dpkg_arch}" == "${DEB_ARCH}" ] || DEB_ARCH=${dpkg_arch}
+  }
+  ARCH=${DEB_ARCH}
+else
+  if [ "${arch}" ]
+  then
+    SUF=zst
+    ARCH=`uname -m`
+  else
+    SUF=rpm
+    ARCH=${RPM_ARCH}
+  fi
+fi
+
+get_available_packages
+
+[ "$PKG_AVAILABLE}" ] || {
+  echo "No packages for version ${PKG_VER} are currently available. Exiting."
+  exit 1
+}
+
+[ "$1" ] && {
+  # If invoked with -i argument, present a menu of options to select from
+  if [ "$1" == "-i" ]
+  then
+    shift
+    PKG_NAMES="$*"
+    [ "${PKG_AVAILABLE}" ] && {
+      echo "Currently available MusicPlayerPlus packages:"
+      echo ""
+      for avaipkg in ${PKG_AVAILABLE}
+      do
+        echo "$avaipkg"
+      done
+      echo ""
+    }
+    while true
+    do
+      PS3="${BOLD}Please enter your desire (numeric or text): ${NORMAL}"
+      options=("Install All" "Install Selected" "Quit")
+      select opt in "${options[@]}"
+      do
+        case "$opt,$REPLY" in
+            "Install All",*|*,"Install All")
+                PKG_NAMES="${PKG_AVAILABLE}"
+                break 2
+                ;;
+            "Install Selected",*|*,"Install Selected")
+                install_selected
+                PKG_NAMES="${PKG_SELECTED}"
+                break 2
+                ;;
+            "Quit",*|*,"Quit"|"quit",*|*,"quit")
+                printf "\nExiting\n"
+                exit 0
+                ;;
+        esac
+      done
+    done
+  else
+    PKG_NAMES="$*"
+  fi
+}
+
+[ "${PKG_NAMES}" ] || {
+  echo "No valid Package names specified. Exiting."
+  exit 1
+}
+
+for PKG_NAME in ${PKG_NAMES}
+do
+  if [ "${arch}" ]
+  then
+    PKG="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}-${ARCH}.pkg.tar.${SUF}"
+  else
+    PKG="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF}"
+  fi
+  [ -f "${PKG}" ] || {
+    echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF} not found."
+    for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
+    do
+      [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
+        echo "Found existing packages:"
+        echo "${pkgs}"
+      }
+    done
+    echo ""
+    continue
+  }
+
+  echo "Installing ${PKG}"
   if [ "${debian}" ]
   then
-    SUF=deb
-    [ "${have_dpkg}" ] && {
-      dpkg_arch=`dpkg --print-architecture`
-      [ "${dpkg_arch}" == "${DEB_ARCH}" ] || DEB_ARCH=${dpkg_arch}
-    }
-    ARCH=${DEB_ARCH}
+    if [ "${have_apt}" ]
+    then
+      sudo apt install "${PKG}"
+    else
+      if [ "${have_dpkg}" ]
+      then
+        sudo dpkg -i "${PKG}"
+      else
+        echo "Cannot locate either apt or dpkg to install. Skipping."
+      fi
+    fi
   else
     if [ "${arch}" ]
     then
-      SUF=zst
-      ARCH=`uname -m`
+      if [ "${have_pac}" ]
+      then
+        sudo pacman -U "${PKG}"
+      else
+        echo "Cannot locate pacman to install. Skipping."
+      fi
     else
-      SUF=rpm
-      ARCH=${RPM_ARCH}
+      if [ "${have_yum}" ]
+      then
+        sudo yum localinstall "${PKG}"
+      else
+        if [ "${have_rpm}" ]
+        then
+          sudo rpm -i "${PKG}"
+        else
+          echo "Cannot locate either yum or rpm to install. Skipping."
+        fi
+      fi
     fi
   fi
-
-  get_available_packages
-
-  [ "$PKG_AVAILABLE}" ] || {
-    echo "No packages for version ${PKG_VER} are currently available. Exiting."
-    exit 1
-  }
-
-  [ "$1" ] && {
-    # If invoked with -i argument, present a menu of options to select from
-    if [ "$1" == "-i" ]
-    then
-      shift
-      PKG_NAMES="$*"
-      [ "${PKG_AVAILABLE}" ] && {
-        echo "Currently available MusicPlayerPlus packages:"
-        echo ""
-        for avaipkg in ${PKG_AVAILABLE}
-        do
-          echo "$avaipkg"
-        done
-        echo ""
-      }
-      while true
-      do
-        PS3="${BOLD}Please enter your desire (numeric or text): ${NORMAL}"
-        options=("Install All" "Install Selected" "Quit")
-        select opt in "${options[@]}"
-        do
-          case "$opt,$REPLY" in
-              "Install All",*|*,"Install All")
-                  PKG_NAMES="${PKG_AVAILABLE}"
-                  break 2
-                  ;;
-              "Install Selected",*|*,"Install Selected")
-                  install_selected
-                  PKG_NAMES="${PKG_SELECTED}"
-                  break 2
-                  ;;
-              "Quit",*|*,"Quit"|"quit",*|*,"quit")
-                  printf "\nExiting\n"
-                  exit 0
-                  ;;
-          esac
-        done
-      done
-    else
-      PKG_NAMES="$*"
-    fi
-  }
-
-  [ "${PKG_NAMES}" ] || {
-    echo "No valid Package names specified. Exiting."
-    exit 1
-  }
-
-  for PKG_NAME in ${PKG_NAMES}
-  do
-    PKG="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF}"
-    [ -f "${PKG}" ] || {
-      echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${ARCH}.${SUF} not found."
-      for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
-      do
-        [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
-          echo "Found existing packages:"
-          echo "${pkgs}"
-        }
-      done
-      echo ""
-      continue
-    }
-
-    echo "Installing ${PKG}"
-    if [ "${debian}" ]
-    then
-      if [ "${have_apt}" ]
-      then
-        sudo apt install "${PKG}"
-      else
-        if [ "${have_dpkg}" ]
-        then
-          sudo dpkg -i "${PKG}"
-        else
-          echo "Cannot locate either apt or dpkg to install. Skipping."
-        fi
-      fi
-    else
-      if [ "${arch}" ]
-      then
-        if [ "${have_pac}" ]
-        then
-          sudo pacman -U "${PKG}"
-        else
-          echo "Cannot locate pacman to install. Skipping."
-        fi
-      else
-        if [ "${have_yum}" ]
-        then
-          sudo yum localinstall "${PKG}"
-        else
-          if [ "${have_rpm}" ]
-          then
-            sudo rpm -i "${PKG}"
-          else
-            echo "Cannot locate either yum or rpm to install. Skipping."
-          fi
-        fi
-      fi
-    fi
-  done
-fi
+done
