Remove check for macOS from Uninstall script

diff --git a/Uninstall b/Uninstall
--- a/Uninstall
+++ b/Uninstall
@@ -1,66 +1,60 @@
 #!/bin/bash
 
-plat=`uname -s`
-if [ "$plat" == "Darwin" ]
+debian=
+arch=
+have_apt=`type -p apt`
+have_dpkg=`type -p dpkg`
+have_rpm=`type -p rpm`
+have_dnf=`type -p dnf`
+have_yum=`type -p yum`
+have_pac=`type -p pacman`
+[ -f /etc/os-release ] && . /etc/os-release
+[ "${ID_LIKE}" == "debian" ] && debian=1
+[ "${ID}" == "arch" ] || [ "${ID_LIKE}" == "arch" ] && arch=1
+[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
+[ "${arch}" ] || [ "${debian}" ] || {
+  echo "${ID_LIKE}" | grep debian > /dev/null && debian=1
+}
+
+PKG=musicplayerplus
+[ "${debian}" ] || [ "${arch}" ] || PKG=MusicPlayerPlus
+
+if [ "${debian}" ]
 then
-    ./macUninstall
-else
-  debian=
-  arch=
-  have_apt=`type -p apt`
-  have_dpkg=`type -p dpkg`
-  have_rpm=`type -p rpm`
-  have_dnf=`type -p dnf`
-  have_yum=`type -p yum`
-  have_pac=`type -p pacman`
-  [ -f /etc/os-release ] && . /etc/os-release
-  [ "${ID_LIKE}" == "debian" ] && debian=1
-  [ "${ID}" == "arch" ] || [ "${ID_LIKE}" == "arch" ] && arch=1
-  [ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
-  [ "${arch}" ] || [ "${debian}" ] || {
-    echo "${ID_LIKE}" | grep debian > /dev/null && debian=1
-  }
-
-  PKG=musicplayerplus
-  [ "${debian}" ] || [ "${arch}" ] || PKG=MusicPlayerPlus
-
-  if [ "${debian}" ]
+  if [ "${have_apt}" ]
   then
-    if [ "${have_apt}" ]
+    sudo apt remove "${PKG}" -y
+  else
+    if [ "${have_dpkg}" ]
     then
-      sudo apt remove "${PKG}" -y
+      sudo dpkg -r "${PKG}"
     else
-      if [ "${have_dpkg}" ]
-      then
-        sudo dpkg -r "${PKG}"
-      else
-        echo "Cannot locate either apt or dpkg to remove. Skipping."
-      fi
+      echo "Cannot locate either apt or dpkg to remove. Skipping."
+    fi
+  fi
+else
+  if [ "${arch}" ]
+  then
+    if [ "${have_pac}" ]
+    then
+      sudo pacman -Rs "${PKG}"
+    else
+      echo "Cannot locate pacman to remove. Skipping."
     fi
   else
-    if [ "${arch}" ]
+    if [ "${have_dnf}" ]
     then
-      if [ "${have_pac}" ]
-      then
-        sudo pacman -Rs "${PKG}"
-      else
-        echo "Cannot locate pacman to remove. Skipping."
-      fi
+      sudo dnf remove "${PKG}"
     else
-      if [ "${have_dnf}" ]
+      if [ "${have_yum}" ]
       then
-        sudo dnf remove "${PKG}"
+        sudo yum remove "${PKG}"
       else
-        if [ "${have_yum}" ]
+        if [ "${have_rpm}" ]
         then
-          sudo yum remove "${PKG}"
+          sudo rpm -e "${PKG}"
         else
-          if [ "${have_rpm}" ]
-          then
-            sudo rpm -e "${PKG}"
-          else
-            echo "Cannot locate either yum or rpm to remove. Skipping."
-          fi
+          echo "Cannot locate either yum or rpm to remove. Skipping."
         fi
       fi
     fi
